### ISSUE TITLE
Template Tag "trans" to "translate"

### ISSUE THREAD

**Issue by GitRon** [adamchainz/django-upgrade#432] opened 2024-02-27 15:25 UTC
### Description

Hi everyone! 👋 

I just learned that the [Django docs](
https://docs.djangoproject.com/en/3.2/topics/i18n/translation/#translate-template-tag) encourage to use `{% translate %}` instead of `{% trans %}`

> Changed in Django 3.1:
> The trans tag was renamed to translate. The trans tag is still supported as an alias for backwards compatibility.

This might be a worthy feature for this package, right?

Best regards  
Ronny

**Comment by adamchainz** [comment] 2024-02-27 15:59
Duplicate of #235. I haven't added any template functionality yet, I think it may be better as part of a template formatter tool. See https://forum.djangoproject.com/t/django-template-style-guide-ticket-14831/28177 for ongoing discussion.

**Comment by GitRon** [comment] 2024-02-27 16:00
Oh, sorry mate! I used the search but was apparently blind... 🙈

**Closed** 2024-02-27 15:59 UTC
