### ISSUE TITLE
Check for unnecessary r strings in path

### ISSUE THREAD

**Issue by pinguin999** [adamchainz/django-upgrade#380] opened 2023-09-05 09:55 UTC
### Description

Hi 

we upgraded a lot of re_path to path and ended with a lot of places where the pathes looked like this:

```python
path(r'/bal/foo'.....)
```

Is it possible to remove the unnecessary **r**?

 ```python
path('/bal/foo'.....)
```

**Comment by UnknownPlatypus** [comment] 2023-11-23 21:33
I don't think `django-upgrade` can create this situation given how `convert_path_syntax` work. Would be nice to have a reproducible exemple if I'm wrong @pinguin999 

Otherwise maybe this is just some `path` urls written that way initially ?
In that case, we could have another fixer to handle that case.

**Comment by adamchainz** [comment] 2023-11-23 22:12
If this issue was not caused by django-upgrade, I would close the issue. Removing unnecessary `r` prefixes sounds like a general Python formatting feature to me.

**Closed** 2024-02-11 22:22 UTC
